---
spring:
  profiles:
    active:
      - dev

---
spring:
  profiles: dev  # 开发模式
    application:
      name: dictservice-provider-user-dev

---
spring:
  profiles:
    active:
      - test

---
spring:
  profiles: test  # 测试模式
    application:
      name: dictservice-provider-user-test
